baseurl: /jekyll        # the subpath of your site, e.g. /blog
url: ""                 # the base hostname & protocol for your site, e.g. http://example.com
title: William Hao
description: a blog of jekyll.
email: haoguanjun@gmail.com
github_username: haoguanjun
paginate: 10
gems:
  - jekyll-feed
  - jekyll-avatar 
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
